@startuml
allowmixing

title Static View - key_value_storage

!include kvs_interface.puml


skinparam package {
    BackgroundColor #E0E0D0
    BorderColor Black
    backgroundColor<<feature>> yellow
}

skinparam component {
    backgroundColor<<component>> white
}

' Define Features
package "key_value_storage" <<feature>> {
    component kvs <<component>>
    component fs <<component>>
    component tiny_json <<component>>
}

kvs -u- Kvs

kvs  ..>  tiny_json : use
kvs  ..>  fs : use


@enduml
